#------------------------------------------------------------------
# 								    
# Name        - relocate_s390.msg				    
# 								    
# Function    -                                                    
# 								    
# Name	       - Neale Ferguson					    
# 								    
# Date        - October, 2007   				    
# 								    
#------------------------------------------------------------------

#------------------------------------------------------------------
#                   L I C E N S E                                  
#------------------------------------------------------------------

#==================================================================
# 								    
# CDDL HEADER START						    
# 								    
# The contents of this file are subject to the terms of the	    
# Common Development and Distribution License, Version 1.0 only    
# (the "License").  You may not use this file except in compliance 
# with the License.						    
# 								    
# You can obtain a copy of the license at: 			    
# - usr/src/OPENSOLARIS.LICENSE, or,				    
# - http://www.opensolaris.org/os/licensing.			    
# See the License for the specific language governing permissions  
# and limitations under the License.				    
# 								    
# When distributing Covered Code, include this CDDL HEADER in each 
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with    
# the fields enclosed by brackets "[]" replaced with your own      
# identifying information: 					    
# Portions Copyright [yyyy] [name of copyright owner]		    
# 								    
# CDDL HEADER END						    
# 								    
#==================================================================

@ MSG_R_390_NONE		"R_390_NONE"
@ MSG_R_390_8			"R_390_8"
@ MSG_R_390_12			"R_390_12"
@ MSG_R_390_16			"R_390_16"
@ MSG_R_390_32			"R_390_32"
@ MSG_R_390_PC32		"R_390_PC32"
@ MSG_R_390_GOT12		"R_390_GOT12"
@ MSG_R_390_GOT32		"R_390_GOT32"
@ MSG_R_390_PLT32		"R_390_PLT32"
@ MSG_R_390_COPY		"R_390_COPY"
@ MSG_R_390_GLOB_DAT		"R_390_GLOB_DAT"
@ MSG_R_390_JMP_SLOT		"R_390_JMP_SLOT"
@ MSG_R_390_RELATIVE		"R_390_RELATIVE"
@ MSG_R_390_GOTOFF32		"R_390_GOTOFF32"
@ MSG_R_390_GOTPC		"R_390_GOTPC"
@ MSG_R_390_GOT16		"R_390_GOT16"
@ MSG_R_390_PC16		"R_390_PC16"
@ MSG_R_390_PC16DBL		"R_390_PC16DBL"
@ MSG_R_390_PLT16DBL		"R_390_PLT16DBL"
@ MSG_R_390_PC32DBL		"R_390_PC32DBL"
@ MSG_R_390_PLT32DBL		"R_390_PLT32DBL"
@ MSG_R_390_GOTPCDBL		"R_390_GOTPCDBL"
@ MSG_R_390_64			"R_390_64"
@ MSG_R_390_PC64		"R_390_PC64"
@ MSG_R_390_GOT64		"R_390_GOT64"
@ MSG_R_390_PLT64		"R_390_PLT64"
@ MSG_R_390_GOTENT		"R_390_GOTENT"
@ MSG_R_390_GOTOFF16		"R_390_GOTOFF16"
@ MSG_R_390_GOTOFF64		"R_390_GOTOFF64"
@ MSG_R_390_GOTPLT12		"R_390_GOTPLT12"
@ MSG_R_390_GOTPLT16		"R_390_GOTPLT16"
@ MSG_R_390_GOTPLT32		"R_390_GOTPLT32"
@ MSG_R_390_GOTPLT64		"R_390_GOTPLT64"
@ MSG_R_390_GOTPLTENT		"R_390_GOTPLTENT"
@ MSG_R_390_PLTOFF16		"R_390_PLTOFF16"
@ MSG_R_390_PLTOFF32		"R_390_PLTOFF32"
@ MSG_R_390_PLTOFF64		"R_390_PLTOFF64"
@ MSG_R_390_TLS_LOAD		"R_390_TLS_LOAD"
@ MSG_R_390_TLS_GDCALL		"R_390_TLS_GDCALL"
@ MSG_R_390_TLS_LDCALL		"R_390_TLS_LDCALL"
@ MSG_R_390_TLS_GD32		"R_390_TLS_GD32"
@ MSG_R_390_TLS_GD64		"R_390_TLS_GD64"
@ MSG_R_390_TLS_GOTIE12		"R_390_TLS_GOTIE12"
@ MSG_R_390_TLS_GOTIE32		"R_390_TLS_GOTIE32"
@ MSG_R_390_TLS_GOTIE64		"R_390_TLS_GOTIE64"
@ MSG_R_390_TLS_LDM32		"R_390_TLS_LDM32"
@ MSG_R_390_TLS_LDM64		"R_390_TLS_LDM64"
@ MSG_R_390_TLS_IE32		"R_390_TLS_IE32"
@ MSG_R_390_TLS_IE64		"R_390_TLS_IE64"
@ MSG_R_390_TLS_IEENT		"R_390_TLS_IEENT"
@ MSG_R_390_TLS_LE32		"R_390_TLS_LE32"
@ MSG_R_390_TLS_LE64		"R_390_TLS_LE64"
@ MSG_R_390_TLS_LDO32		"R_390_TLS_LDO32"
@ MSG_R_390_TLS_LDO64		"R_390_TLS_LDO64"
@ MSG_R_390_TLS_DTPMOD		"R_390_TLS_DTPMOD"
@ MSG_R_390_TLS_DTPOFF		"R_390_TLS_DTPOFF"
@ MSG_R_390_TLS_TPOFF		"R_390_TLS_TPOFF"
@ MSG_R_390_20			"R_390_20"
@ MSG_R_390_GOT20		"R_390_GOT20"
@ MSG_R_390_GOTPLT20		"R_390_GOTPLT20"
@ MSG_R_390_TLS_GOTIE20		"R_390_TLS_GOTIE20"
@ MSG_R_390_GNU_VTINHERIT	"R_390_GNU_VTINHERIT"
@ MSG_R_390_GNU_VTENTRY		"R_390_GNU_VTENTRY"
