#
# Copyright (c) 1997-2001 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma	ident	"@(#)Makefile	1.2	01/05/03 SMI"
#
# lib/krb5/db2/s390x/Makefile

MAPDIR= ../spec/s390x

include ../Makefile.com

install: all $(ROOTLIBDIR) $(ROOTLIBS) $(ROOTLINKS)
