#
# Copyright 1997-2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.4	02/03/26 SMI"
#

MAPDIR= ../spec/s390x

include ../Makefile.com

install: all $(ROOTLIBDIR) $(ROOTLIBS) $(ROOTLINKS)
